### ISSUE TITLE
Lowe et al. TODO list

### ISSUE THREAD

**Issue by slayoo** [open-atmos/PySDM#604]
- [ ] 0.1 vs. 0.2 film thickness

**Comment by slayoo** [comment]
@claresinger any hints regarding the 0.1 vs. 0.2 dilemma based on the FORTRAN code? :)

**Comment by claresinger** [comment]
Hi @slayoo. I'm still waiting to receive the fortran code actually. The version they sent seems to be the version *without* the compressed film model implemented unfortunately.

**Comment by claresinger** [comment]
@slayoo Update: Dan Partridge will send the code on Monday.

**Comment by slayoo** [comment]
@claresinger any news here? :)

**Comment by claresinger** [comment]
See my email to you and Dan. Fig 1 seems like it was made without calling the parcel model actually. Or maybe there are just some more post-processing scripts missing. The plot scripts try to open files that are not produced as output from the parcel model directly... WIP!

**Comment by claresinger** [comment]
> [ ] 0.1 vs. 0.2 film thickness

More TODOs post merge https://github.com/atmos-cloud-sim-uj/PySDM-examples/pull/127
[ ] Why does Fig 1c and 1d not match paper? Changing `delta_min = 0.1` (vs. 0.2 in paper) helps. Maybe also the temperature is wrong? The temperature is not specified in the paper.
[ ] Parcel simulations in Fig 2 need short timestep, see #746 about adding piece-wise linear approximation to pressure profile.
[ ] Size distribution in Fig 2c indicates potential reasons for CDNC mismatches. Bulk calculation for `NUM` aerosol is ~1 um too small at final step.

More TODOs with https://github.com/atmos-cloud-sim-uj/PySDM-examples/pull/51

**Comment by slayoo** [comment]
@claresinger let's summarise what is still needed (and feasible) here

**Comment by claresinger** [comment]
The example is mostly consistent with the figures in Lowe et al 2019, with the following outstanding discrepancies:
- [ ] Fig 1c and 1d not match paper with the parameter values as specified. Changing `delta_min = 0.1` (vs. 0.2 in paper) helps. Maybe also the temperature is wrong? The temperature is not specified in the paper.
- [ ] In Fig 2c the bulk calculation for NUM aerosol is ~1 um too small. Indicates the issues here are not necessarily with the surface partitioning.
- [ ] All constants/parameter values should ideally be checked by someone from Dr. Riipinen's group against their code/Sam Lowe's files.
- [ ] The PySDM solver behavior means that parcel results are very sensitive to dz (aka timestep). This behavior is also seen in pyrcel example (#776). https://github.com/open-atmos/PySDM-examples/pull/164 might fix this. Or #746 might be another solution.

**Comment by claresinger** [comment]
Closing in favor of #1247 with updated information and checklist.
